In [1]:
import pandas as pd

In [2]:
students = pd.read_csv('Pandas_Practice_Pack/students.csv')

In [3]:
students.head(2)

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16

Select the first 5 rows using iloc.

In [4]:
students.iloc[:5]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01

Select rows at positions 5 through 10.

In [5]:
students.iloc[4:15]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18

Select the first 5 rows and the first 3 columns.

In [6]:
students.iloc[:5,0:3]

  student_id    name  age
0      ST001   Aarav   18
1      ST002    Diya   23
2      ST003  Ishaan   19
3      ST004   Meera   20
4      ST005   Kabir   20

Find students whose marks are greater than 70.

In [7]:
students[students['marks'] > 70]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05

Find students whose marks are less than 50.

In [8]:
students[students['marks'] <= 50]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26

Find students whose marks equal 80.

In [9]:
students[students['marks'] == 80]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05

Find students from Pune.

In [10]:
students[students['city'] == 'Pune']

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14

Find students from Pune who scored more than 70.

In [11]:
students[(students['city'] == 'Pune') & (students['marks'] >= 70)]

Empty DataFrame
Columns: [student_id, name, age, city, course, marks, attendance, study_hours_per_week, placement_status, join_date]
Index: []

Find students with marks greater than 80 and attendance greater than 75.

In [12]:
students[(students['marks'] > 80) & (students['attendance'] > 75)]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03

Find students from Pune or Mumbai.

In [13]:
students[students['city'].isin(['Pune' , "Mumbai"])]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14

In [14]:
students[(students['city'] == 'Pune') | (students['city'] == 'Mumbai')]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14

Find students studying Computer or IT.

In [15]:
students[students['course'].isin(['IT' , 'Computer'])]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06

Sort students by marks in ascending order.

In [16]:
students.sort_values(by='marks')

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18

Sort students by marks in descending order.

In [17]:
students.sort_values(by='marks' , ascending=False)

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18

Find the 5 students with the highest marks.

In [18]:
students.sort_values(by='marks' , ascending=False).head(5)

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05

Find the 5 students with the lowest marks.

In [19]:
students.sort_values(by='marks' , ascending=False).tail(5)

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18

Sort by course and then marks in descending order.

In [20]:
students.sort_values(by=['course' , 'marks'] , ascending=[True , False])

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17

Find students aged 20 or above.

In [21]:
students[students['age'] >= 20]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26

Find students whose marks are between 60 and 80, inclusive.

In [22]:
students[students['marks'].apply(lambda x : x > 60 and  x < 80)]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22

Filter students using isin() for a selected list of cities.

In [23]:
students[students['city'].isin(['Pune'])]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14

Select the student with a specific student_id using loc after setting that column as the index.

In [24]:
students.loc[students['student_id'] == 'ST003']

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21