Level 5 — Logic, functions, apply() and map() (Questions 96–115)

In [16]:
import numpy as np
import pandas as pd

In [2]:
students = pd.read_csv('Pandas_Practice_Pack/students.csv')
students.head()

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01

Write a function that returns "Pass" or "Fail" from a mark.

In [3]:
def Check_pass_Fail(marks) :
    return 'Pass' if marks >= 40 else 'Fail'

In [4]:
students['Status_Of_Result']= students['marks'].apply(Check_pass_Fail)
students

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date,Status_Of_Result
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12,Pass
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16,Pass
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21,Pass
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21,Fail
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01,Pass
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11,Pass
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26,Pass
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17,Pass
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29,Pass
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23,Pass
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25,Pass
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17,Fail
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05,Pass
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03,Pass
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18,Pass
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13,Pass
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15,Pass
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20,Pass
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19,Pass
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03,Pass
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18,Fail
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09,Pass
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14,Pass
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22,Pass
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05,Pass
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04,Pass
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14,Pass
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03,Pass
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06,Pass
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26,Pass

Use apply() to create a pass/fail column.

In [5]:
students['By_Apply_CHECK'] = students['marks'].apply(lambda x : 'Pass' if  x >= 40 else 'Fail')
students

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date,Status_Of_Result,By_Apply_CHECK
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12,Pass,Pass
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16,Pass,Pass
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21,Pass,Pass
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21,Fail,Fail
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01,Pass,Pass
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11,Pass,Pass
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26,Pass,Pass
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17,Pass,Pass
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29,Pass,Pass
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23,Pass,Pass
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25,Pass,Pass
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17,Fail,Fail
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05,Pass,Pass
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03,Pass,Pass
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18,Pass,Pass
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13,Pass,Pass
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15,Pass,Pass
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20,Pass,Pass
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19,Pass,Pass
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03,Pass,Pass
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18,Fail,Fail
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09,Pass,Pass
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14,Pass,Pass
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22,Pass,Pass
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05,Pass,Pass
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04,Pass,Pass
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14,Pass,Pass
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03,Pass,Pass
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06,Pass,Pass
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26,Pass,Pass

Use lambda to add 10 to each mark.

In [6]:
students['marks'] = students['marks'].apply(lambda x : x + 10)
students

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date,Status_Of_Result,By_Apply_CHECK
0,ST001,Aarav,18,Kolhapur,IT,88.0,62.0,16,Not Placed,2024-06-12,Pass,Pass
1,ST002,Diya,23,Mumbai,ENTC,54.0,98.0,29,Placed,2023-06-16,Pass,Pass
2,ST003,Ishaan,19,Pune,ENTC,53.0,68.0,14,Not Placed,2023-09-21,Pass,Pass
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21,Fail,Fail
4,ST005,Kabir,20,Mumbai,Computer,57.0,68.0,26,Placed,2023-12-01,Pass,Pass
5,ST006,Anaya,22,Kolhapur,Computer,102.0,NaN,31,Placed,2024-10-11,Pass,Pass
6,ST007,Rohan,18,Kolhapur,ENTC,107.0,79.0,25,Not Placed,2024-05-26,Pass,Pass
7,ST008,Gauri,23,Nagpur,Mechanical,52.0,57.0,7,Not Placed,2024-08-17,Pass,Pass
8,ST009,Vivek,20,NaN,Mechanical,54.0,79.0,12,Interviewing,2023-11-29,Pass,Pass
9,ST010,Nisha,20,Mumbai,ENTC,61.0,97.0,12,Not Placed,2023-08-23,Pass,Pass
10,ST011,Aditya,20,Nagpur,Mechanical,77.0,79.0,5,Not Placed,2024-07-25,Pass,Pass
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17,Fail,Fail
12,ST013,Om,21,Aurangabad,IT,89.0,86.0,18,Not Placed,2023-10-05,Pass,Pass
13,ST014,Priya,22,Kolhapur,ENTC,95.0,90.0,29,Not Placed,2023-12-03,Pass,Pass
14,ST015,Kunal,22,Aurangabad,Computer,62.0,63.0,5,Placed,2023-08-18,Pass,Pass
15,ST016,Ira,23,Solapur,ENTC,88.0,65.0,6,Not Placed,2023-12-13,Pass,Pass
16,ST017,Rahul,22,Kolhapur,ENTC,86.0,84.0,2,Placed,2024-05-15,Pass,Pass
17,ST018,Sana,20,Satara,Computer,104.0,NaN,20,Not Placed,2023-08-20,Pass,Pass
18,ST019,Dev,23,Kolhapur,ENTC,77.0,55.0,13,Placed,2024-08-19,Pass,Pass
19,ST020,Pooja,23,Nagpur,IT,88.0,74.0,25,Not Placed,2024-03-03,Pass,Pass
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18,Fail,Fail
21,ST022,Maya,19,Pune,IT,71.0,74.0,7,Placed,2024-06-09,Pass,Pass
22,ST023,Neel,22,Nashik,IT,79.0,59.0,32,Not Placed,2023-10-14,Pass,Pass
23,ST024,Tara,21,Nagpur,ENTC,81.0,93.0,14,Interviewing,2023-12-22,Pass,Pass
24,ST025,Yash,20,Aurangabad,ENTC,90.0,96.0,30,Placed,2023-10-05,Pass,Pass
25,ST026,Aditi,20,Pune,ENTC,62.0,59.0,16,Not Placed,2023-06-04,Pass,Pass
26,ST027,Sahil,23,Pune,IT,52.0,100.0,6,Placed,2024-08-14,Pass,Pass
27,ST028,Riya,22,Nagpur,Mechanical,69.0,59.0,33,Not Placed,2024-03-03,Pass,Pass
28,ST029,Manav,22,Aurangabad,IT,56.0,91.0,32,Not Placed,2023-09-06,Pass,Pass
29,ST030,Kavya,23,Solapur,Mechanical,54.0,61.0,29,Not Placed,2024-01-26,Pass,Pass

Use map() to shorten placement-status labels.

In [7]:
status_map = {
    'Placed': 'Yes',
    'Not Placed': 'No'
}
students['placement_status'].map(status_map)

0      No
1     Yes
2      No
3     NaN
4     Yes
5     Yes
6      No
7      No
8     NaN
9      No
10     No
11    NaN
12     No
13     No
14    Yes
15     No
16    Yes
17     No
18    Yes
19     No
20    Yes
21    Yes
22     No
23    NaN
24    Yes
25     No
26    Yes
27     No
28     No
29     No
Name: placement_status, dtype: str

Create a function that checks whether a student is from Pune.

In [8]:
def is_from_pune(city):
    return city == 'Pune'

In [9]:
students['city'].apply(is_from_pune)

0     False
1     False
2      True
3      True
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21     True
22    False
23    False
24    False
25     True
26     True
27    False
28    False
29    False
Name: city, dtype: bool

Use apply() to find students with marks greater than 80.

In [10]:
students[students['marks'].apply(lambda x : x > 80)]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date,Status_Of_Result,By_Apply_CHECK
0,ST001,Aarav,18,Kolhapur,IT,88.0,62.0,16,Not Placed,2024-06-12,Pass,Pass
5,ST006,Anaya,22,Kolhapur,Computer,102.0,NaN,31,Placed,2024-10-11,Pass,Pass
6,ST007,Rohan,18,Kolhapur,ENTC,107.0,79.0,25,Not Placed,2024-05-26,Pass,Pass
12,ST013,Om,21,Aurangabad,IT,89.0,86.0,18,Not Placed,2023-10-05,Pass,Pass
13,ST014,Priya,22,Kolhapur,ENTC,95.0,90.0,29,Not Placed,2023-12-03,Pass,Pass
15,ST016,Ira,23,Solapur,ENTC,88.0,65.0,6,Not Placed,2023-12-13,Pass,Pass
16,ST017,Rahul,22,Kolhapur,ENTC,86.0,84.0,2,Placed,2024-05-15,Pass,Pass
17,ST018,Sana,20,Satara,Computer,104.0,NaN,20,Not Placed,2023-08-20,Pass,Pass
19,ST020,Pooja,23,Nagpur,IT,88.0,74.0,25,Not Placed,2024-03-03,Pass,Pass
23,ST024,Tara,21,Nagpur,ENTC,81.0,93.0,14,Interviewing,2023-12-22,Pass,Pass
24,ST025,Yash,20,Aurangabad,ENTC,90.0,96.0,30,Placed,2023-10-05,Pass,Pass

Use apply() to classify students by study hours: Low (below 10), Medium (10–20), High (above 20).

In [11]:
students['study_hours_per_week'].apply(lambda x  : 'High' if x > 20 else 'Medium' if x > 10 and x <20 else 'Low' )

0     Medium
1       High
2     Medium
3       High
4       High
5       High
6       High
7        Low
8     Medium
9     Medium
10       Low
11    Medium
12    Medium
13      High
14       Low
15       Low
16       Low
17       Low
18    Medium
19      High
20       Low
21       Low
22      High
23    Medium
24      High
25    Medium
26       Low
27      High
28      High
29      High
Name: study_hours_per_week, dtype: str

Create a column that combines each student's name and course.

In [12]:
students['Combine'] = students['name'] +  "-"+ students['course']
students['Combine']

0              Aarav-IT
1             Diya-ENTC
2           Ishaan-ENTC
3              Meera-IT
4        Kabir-Computer
5        Anaya-Computer
6            Rohan-ENTC
7      Gauri-Mechanical
8      Vivek-Mechanical
9            Nisha-ENTC
10    Aditya-Mechanical
11        Sara-Computer
12                Om-IT
13           Priya-ENTC
14       Kunal-Computer
15             Ira-ENTC
16           Rahul-ENTC
17        Sana-Computer
18             Dev-ENTC
19             Pooja-IT
20          Arjun-Civil
21              Maya-IT
22              Neel-IT
23            Tara-ENTC
24            Yash-ENTC
25           Aditi-ENTC
26             Sahil-IT
27      Riya-Mechanical
28             Manav-IT
29     Kavya-Mechanical
Name: Combine, dtype: str

Find students whose names start with a chosen letter using string methods.

In [13]:
students[students['name'].str.startswith('A', na=False)]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date,Status_Of_Result,By_Apply_CHECK,Combine
0,ST001,Aarav,18,Kolhapur,IT,88.0,62.0,16,Not Placed,2024-06-12,Pass,Pass,Aarav-IT
5,ST006,Anaya,22,Kolhapur,Computer,102.0,NaN,31,Placed,2024-10-11,Pass,Pass,Anaya-Computer
10,ST011,Aditya,20,Nagpur,Mechanical,77.0,79.0,5,Not Placed,2024-07-25,Pass,Pass,Aditya-Mechanical
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18,Fail,Fail,Arjun-Civil
25,ST026,Aditi,20,Pune,ENTC,62.0,59.0,16,Not Placed,2023-06-04,Pass,Pass,Aditi-ENTC

Convert all names to uppercase.

In [14]:
students['name'].apply(lambda x : x.upper())

0      AARAV
1       DIYA
2     ISHAAN
3      MEERA
4      KABIR
5      ANAYA
6      ROHAN
7      GAURI
8      VIVEK
9      NISHA
10    ADITYA
11      SARA
12        OM
13     PRIYA
14     KUNAL
15       IRA
16     RAHUL
17      SANA
18       DEV
19     POOJA
20     ARJUN
21      MAYA
22      NEEL
23      TARA
24      YASH
25     ADITI
26     SAHIL
27      RIYA
28     MANAV
29     KAVYA
Name: name, dtype: str

In [15]:
students['name'] = students['name'].str.upper()

Find names containing a particular substring.

Use np.where() to create a binary pass/fail column.

In [18]:
students['binary'] = np.where(students['marks'] > 40 , "pass" ,'Fail')

In [19]:
students['binary']

0     pass
1     pass
2     pass
3     Fail
4     pass
5     pass
6     pass
7     pass
8     pass
9     pass
10    pass
11    Fail
12    pass
13    pass
14    pass
15    pass
16    pass
17    pass
18    pass
19    pass
20    Fail
21    pass
22    pass
23    pass
24    pass
25    pass
26    pass
27    pass
28    pass
29    pass
Name: binary, dtype: str

Use np.select() to classify students into multiple performance categories.

In [20]:


conditions = [
    students['marks'] >= 90,
    students['marks'] >= 80,
    students['marks'] >= 70,
    students['marks'] >= 60
]

categories = [
    'Excellent',
    'Very Good',
    'Good',
    'Average'
]

students['performance'] = np.select(
    conditions,
    categories,
    default='Poor'
)

Write a function that accepts a DataFrame and column name and returns its mean.

In [23]:
def mean(df ,column) :
    return df[column].mean()

mean(students , 'marks')

np.float64(74.37037037037037)

Write a function that returns the top N students by marks.

In [25]:
def top(df , n):
    return df[n].sort_values( ascending=False).head(5)
top(students , 'marks')

6     107.0
17    104.0
5     102.0
13     95.0
24     90.0
Name: marks, dtype: float64