In [1]:
import pandas as pd

In [2]:
students = pd.read_csv('Pandas_Practice_Pack/students.csv')
students.head()

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01

Level 4 — Data cleaning (Questions 76–95)

Count missing values in every column.

In [3]:
students.isnull().sum()

student_id              0
name                    0
age                     0
city                    1
course                  0
marks                   3
attendance              2
study_hours_per_week    0
placement_status        0
join_date               0
dtype: int64

In [4]:
students.isna().sum()

student_id              0
name                    0
age                     0
city                    1
course                  0
marks                   3
attendance              2
study_hours_per_week    0
placement_status        0
join_date               0
dtype: int64

Find all rows containing at least one missing value.

In [5]:
students[students.isna().any(axis=1)]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18

Find rows where attendance is missing.

In [6]:
students[students['attendance'].isna()]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20

Find all rows containing at least one missing value.

In [7]:
students[students.isna().any(axis=1)]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18

Fill missing attendance with the mean attendance rounded to one decimal place.

In [8]:
students ['attendance']= students['attendance'].fillna(round(students['attendance'].mean()) )

Fill missing city values with "Unknown".

In [9]:
students['city'] = students['city'].fillna("Unknown")

In [10]:
students

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
5,ST006,Anaya,22,Kolhapur,Computer,92.0,77.0,31,Placed,2024-10-11
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17
8,ST009,Vivek,20,Unknown,Mechanical,44.0,79.0,12,Interviewing,2023-11-29
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15
17,ST018,Sana,20,Satara,Computer,94.0,77.0,20,Not Placed,2023-08-20
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26

Drop rows where marks are missing.

In [11]:
students.dropna(subset=['marks'] , inplace=True)

Drop columns that contain only missing values.

In [12]:
students.dropna(axis=1 , inplace=True)

Find duplicate rows.

In [13]:
students.duplicated()

0     False
1     False
2     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
dtype: bool

Remove exact duplicate rows from a copy of the DataFrame.

In [14]:
students.drop_duplicates()

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
5,ST006,Anaya,22,Kolhapur,Computer,92.0,77.0,31,Placed,2024-10-11
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17
8,ST009,Vivek,20,Unknown,Mechanical,44.0,79.0,12,Interviewing,2023-11-29
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15
17,ST018,Sana,20,Satara,Computer,94.0,77.0,20,Not Placed,2023-08-20
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26

Check the data types before and after cleaning.

In [15]:
students.dtypes

student_id                  str
name                        str
age                       int64
city                        str
course                      str
marks                   float64
attendance              float64
study_hours_per_week      int64
placement_status            str
join_date                   str
dtype: object

Convert join_date to datetime.

In [16]:
students['join_date'] = pd.to_datetime(students['join_date'])

In [17]:
students

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
5,ST006,Anaya,22,Kolhapur,Computer,92.0,77.0,31,Placed,2024-10-11
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17
8,ST009,Vivek,20,Unknown,Mechanical,44.0,79.0,12,Interviewing,2023-11-29
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15
17,ST018,Sana,20,Satara,Computer,94.0,77.0,20,Not Placed,2023-08-20
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26

Extract the year from join_date.

In [18]:
students['join_year'] = students['join_date'].dt.year

Extract the month from join_date.

In [19]:
students['month'] = students['join_date'].dt.month

Extract the weekday from join_date.

In [20]:
students['week'] = students['join_date'].dt.weekday

Replace a chosen city name with another value in a copy of the DataFrame.

In [21]:
students_copy = students.copy()
students_copy['city'] = students_copy['city'].replace('Pune' , "mumbai")

In [22]:
students_copy

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date,join_year,month,week
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12,2024,6,2
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16,2023,6,4
2,ST003,Ishaan,19,mumbai,ENTC,43.0,68.0,14,Not Placed,2023-09-21,2023,9,3
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01,2023,12,4
5,ST006,Anaya,22,Kolhapur,Computer,92.0,77.0,31,Placed,2024-10-11,2024,10,4
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26,2024,5,6
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17,2024,8,5
8,ST009,Vivek,20,Unknown,Mechanical,44.0,79.0,12,Interviewing,2023-11-29,2023,11,2
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23,2023,8,2
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25,2024,7,3
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05,2023,10,3
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03,2023,12,6
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18,2023,8,4
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13,2023,12,2
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15,2024,5,2
17,ST018,Sana,20,Satara,Computer,94.0,77.0,20,Not Placed,2023-08-20,2023,8,6
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19,2024,8,0
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03,2024,3,6
21,ST022,Maya,19,mumbai,IT,61.0,74.0,7,Placed,2024-06-09,2024,6,6
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14,2023,10,5
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22,2023,12,4
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05,2023,10,3
25,ST026,Aditi,20,mumbai,ENTC,52.0,59.0,16,Not Placed,2023-06-04,2023,6,6
26,ST027,Sahil,23,mumbai,IT,42.0,100.0,6,Placed,2024-08-14,2024,8,2
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03,2024,3,6
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06,2023,9,2
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26,2024,1,4

Check whether any marks are below 0 or above 100.

In [23]:
students[(students['marks'] < 0) | (students['marks'] > 100)]

Empty DataFrame
Columns: [student_id, name, age, city, course, marks, attendance, study_hours_per_week, placement_status, join_date, join_year, month, week]
Index: []

In [24]:
students['marks'].apply(lambda x : x < 0 or x > 100)

0     False
1     False
2     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
Name: marks, dtype: bool

Create a cleaning function that reports missing values before and after cleaning.

In [25]:

def drop(df):
    print("Missing values before cleaning:")
    print(df.isnull().sum())

    df_cleared = df.dropna().copy()

    print("\nMissing values after cleaning:")
    print(df_cleared.isnull().sum())

    return df_cleared

students_cleaned = drop(students)

Missing values before cleaning:
student_id              0
name                    0
age                     0
city                    0
course                  0
marks                   0
attendance              0
study_hours_per_week    0
placement_status        0
join_date               0
join_year               0
month                   0
week                    0
dtype: int64

Missing values after cleaning:
student_id              0
name                    0
age                     0
city                    0
course                  0
marks                   0
attendance              0
study_hours_per_week    0
placement_status        0
join_date               0
join_year               0
month                   0
week                    0
dtype: int64