Level 1 — Pandas fundamentals (Questions 16–35)

In [1]:
import pandas as pd

In [2]:
students  = pd.read_csv('Pandas_Practice_Pack/students.csv')

Display the entire DataFrame.

In [3]:
students

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26

Display the first 5 rows using head().

In [4]:
students.head()

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01

Display the first 10 rows.

In [5]:
students.head(10)

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23

Display the last 5 rows using tail().

In [6]:
students.tail()

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26

Find the number of rows and columns using shape.

In [7]:
students.shape

(30, 10)

Display all column names.

In [8]:
students.columns

Index(['student_id', 'name', 'age', 'city', 'course', 'marks', 'attendance',
       'study_hours_per_week', 'placement_status', 'join_date'],
      dtype='str')

Display the index of the DataFrame.

In [9]:
students.index

RangeIndex(start=0, stop=30, step=1)

Check the data types using dtypes.

In [10]:
students.dtypes

student_id                  str
name                        str
age                       int64
city                        str
course                      str
marks                   float64
attendance              float64
study_hours_per_week      int64
placement_status            str
join_date                   str
dtype: object

Display DataFrame information using info().

In [11]:
students.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            30 non-null     str
 1   name                  30 non-null     str
 2   age                   30 non-null     int64
 3   city                  29 non-null     str
 4   course                30 non-null     str
 5   marks                 27 non-null     float64
 6   attendance            28 non-null     float64
 7   study_hours_per_week  30 non-null     int64
 8   placement_status      30 non-null     str
 9   join_date             30 non-null     str
dtypes: float64(2), int64(2), str(6)
memory usage: 2.5 KB

Generate statistical information using describe().

In [12]:
students.describe()

             age      marks  attendance  study_hours_per_week
count  30.000000  27.000000   28.000000             30.000000
mean   21.000000  64.370370   76.821429             18.033333
std     1.640017  17.789686   14.529800             10.297249
min    18.000000  42.000000   55.000000              2.000000
25%    20.000000  46.500000   62.750000              8.250000
50%    21.000000  67.000000   77.000000             16.000000
75%    22.000000  78.000000   90.250000             29.000000
max    23.000000  97.000000  100.000000             33.000000

Select the name column.

In [13]:
students['name']

0      Aarav
1       Diya
2     Ishaan
3      Meera
4      Kabir
5      Anaya
6      Rohan
7      Gauri
8      Vivek
9      Nisha
10    Aditya
11      Sara
12        Om
13     Priya
14     Kunal
15       Ira
16     Rahul
17      Sana
18       Dev
19     Pooja
20     Arjun
21      Maya
22      Neel
23      Tara
24      Yash
25     Aditi
26     Sahil
27      Riya
28     Manav
29     Kavya
Name: name, dtype: str

Select the marks column.

In [14]:
students['marks']

0     78.0
1     44.0
2     43.0
3      NaN
4     47.0
5     92.0
6     97.0
7     42.0
8     44.0
9     51.0
10    67.0
11     NaN
12    79.0
13    85.0
14    52.0
15    78.0
16    76.0
17    94.0
18    67.0
19    78.0
20     NaN
21    61.0
22    69.0
23    71.0
24    80.0
25    52.0
26    42.0
27    59.0
28    46.0
29    44.0
Name: marks, dtype: float64

Select both name and marks.

In [15]:
students[['name' , 'marks']]

      name  marks
0    Aarav   78.0
1     Diya   44.0
2   Ishaan   43.0
3    Meera    NaN
4    Kabir   47.0
5    Anaya   92.0
6    Rohan   97.0
7    Gauri   42.0
8    Vivek   44.0
9    Nisha   51.0
10  Aditya   67.0
11    Sara    NaN
12      Om   79.0
13   Priya   85.0
14   Kunal   52.0
15     Ira   78.0
16   Rahul   76.0
17    Sana   94.0
18     Dev   67.0
19   Pooja   78.0
20   Arjun    NaN
21    Maya   61.0
22    Neel   69.0
23    Tara   71.0
24    Yash   80.0
25   Aditi   52.0
26   Sahil   42.0
27    Riya   59.0
28   Manav   46.0
29   Kavya   44.0

Find the number of students using len().

In [16]:
len(students)

30

In [17]:
students.shape[0]

30

Find all unique cities using unique().

In [18]:
students['city'].unique()

<StringArray>
[  'Kolhapur',     'Mumbai',       'Pune',     'Nagpur',          nan,
 'Aurangabad',    'Solapur',     'Satara',     'Nashik']
Length: 9, dtype: str

Count the unique cities using nunique().

In [19]:
students['city'].nunique(dropna=False)

9

Count students in each city using value_counts().

In [20]:
students['city'].value_counts(dropna=False)

city
Kolhapur      7
Pune          5
Nagpur        5
Aurangabad    4
Mumbai        3
Solapur       2
Satara        2
NaN           1
Nashik        1
Name: count, dtype: int64

Display the name, course, and marks columns.

In [21]:
students[['name' , 'course' , 'marks']]

      name      course  marks
0    Aarav          IT   78.0
1     Diya        ENTC   44.0
2   Ishaan        ENTC   43.0
3    Meera          IT    NaN
4    Kabir    Computer   47.0
5    Anaya    Computer   92.0
6    Rohan        ENTC   97.0
7    Gauri  Mechanical   42.0
8    Vivek  Mechanical   44.0
9    Nisha        ENTC   51.0
10  Aditya  Mechanical   67.0
11    Sara    Computer    NaN
12      Om          IT   79.0
13   Priya        ENTC   85.0
14   Kunal    Computer   52.0
15     Ira        ENTC   78.0
16   Rahul        ENTC   76.0
17    Sana    Computer   94.0
18     Dev        ENTC   67.0
19   Pooja          IT   78.0
20   Arjun       Civil    NaN
21    Maya          IT   61.0
22    Neel          IT   69.0
23    Tara        ENTC   71.0
24    Yash        ENTC   80.0
25   Aditi        ENTC   52.0
26   Sahil          IT   42.0
27    Riya  Mechanical   59.0
28   Manav          IT   46.0
29   Kavya  Mechanical   44.0

Create a copy of the DataFrame.

In [22]:
newDataSet = pd.DataFrame(columns=students.columns)
newDataSet = pd.concat([newDataSet , students])

Save the first 10 rows to a new CSV file.

In [23]:
newDataSet

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26