In [1]:
import pandas as pd

In [2]:
students = pd.read_csv('Pandas_Practice_Pack/students.csv')

In [3]:
students.head(2)

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16

Level 3 — Calculations and new columns (Questions 56–75)

Calculate the average marks.

Calculate the median marks.

In [4]:
print(students['marks'].mean())

64.37037037037037

Find the highest and lowest marks.

In [5]:
students.sort_values(by='marks' , ascending=False).head(1)

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26

In [6]:
students.sort_values(by='marks' , ).head(1)

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14

Calculate the average attendance.

In [7]:
print(students['attendance'].mean())

76.82142857142857

Create a column called passed based on marks greater than or equal to 40.

In [8]:
students['Passed'] = students['marks'].apply(lambda x : 'Passed' if x >= 40 else 'Fail' )

In [9]:
students[['student_id' , "marks" , "Passed"  ]]

   student_id  marks  Passed
0       ST001   78.0  Passed
1       ST002   44.0  Passed
2       ST003   43.0  Passed
3       ST004    NaN    Fail
4       ST005   47.0  Passed
5       ST006   92.0  Passed
6       ST007   97.0  Passed
7       ST008   42.0  Passed
8       ST009   44.0  Passed
9       ST010   51.0  Passed
10      ST011   67.0  Passed
11      ST012    NaN    Fail
12      ST013   79.0  Passed
13      ST014   85.0  Passed
14      ST015   52.0  Passed
15      ST016   78.0  Passed
16      ST017   76.0  Passed
17      ST018   94.0  Passed
18      ST019   67.0  Passed
19      ST020   78.0  Passed
20      ST021    NaN    Fail
21      ST022   61.0  Passed
22      ST023   69.0  Passed
23      ST024   71.0  Passed
24      ST025   80.0  Passed
25      ST026   52.0  Passed
26      ST027   42.0  Passed
27      ST028   59.0  Passed
28      ST029   46.0  Passed
29      ST030   44.0  Passed

Create a column called bonus_marks by adding 5 marks to every student's marks.

In [10]:
students['bonus_marks'] = students["marks"] + 5
students

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date,Passed,bonus_marks
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12,Passed,83.0
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16,Passed,49.0
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21,Passed,48.0
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21,Fail,NaN
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01,Passed,52.0
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11,Passed,97.0
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26,Passed,102.0
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17,Passed,47.0
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29,Passed,49.0
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23,Passed,56.0
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25,Passed,72.0
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17,Fail,NaN
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05,Passed,84.0
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03,Passed,90.0
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18,Passed,57.0
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13,Passed,83.0
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15,Passed,81.0
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20,Passed,99.0
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19,Passed,72.0
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03,Passed,83.0
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18,Fail,NaN
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09,Passed,66.0
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14,Passed,74.0
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22,Passed,76.0
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05,Passed,85.0
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04,Passed,57.0
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14,Passed,47.0
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03,Passed,64.0
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06,Passed,51.0
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26,Passed,49.0

Create total_score by adding marks and attendance.

In [11]:
students['total_score'] = students["marks"] + students['attendance']

Calculate the difference between each student's marks and the class average.

In [12]:
avg = students['marks'].mean()

In [13]:
students['marks'] - avg

0     13.62963
1    -20.37037
2    -21.37037
3          NaN
4    -17.37037
5     27.62963
6     32.62963
7    -22.37037
8    -20.37037
9    -13.37037
10     2.62963
11         NaN
12    14.62963
13    20.62963
14   -12.37037
15    13.62963
16    11.62963
17    29.62963
18     2.62963
19    13.62963
20         NaN
21    -3.37037
22     4.62963
23     6.62963
24    15.62963
25   -12.37037
26   -22.37037
27    -5.37037
28   -18.37037
29   -20.37037
Name: marks, dtype: float64

Create attendance_status: Excellent for attendance >= 90, Good for attendance >= 75 but below 90, and Poor below 75.

In [14]:
students['attendance_status'] = students['attendance'].apply(lambda x: 'Excellent' if x > 90 else 'Good' if x >=75 and x < 90 else 'Poor' )

In [15]:
students

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date,Passed,bonus_marks,total_score,attendance_status
0,ST001,Aarav,18,Kolhapur,IT,78.0,62.0,16,Not Placed,2024-06-12,Passed,83.0,140.0,Poor
1,ST002,Diya,23,Mumbai,ENTC,44.0,98.0,29,Placed,2023-06-16,Passed,49.0,142.0,Excellent
2,ST003,Ishaan,19,Pune,ENTC,43.0,68.0,14,Not Placed,2023-09-21,Passed,48.0,111.0,Poor
3,ST004,Meera,20,Pune,IT,NaN,92.0,29,Interviewing,2023-10-21,Fail,NaN,NaN,Excellent
4,ST005,Kabir,20,Mumbai,Computer,47.0,68.0,26,Placed,2023-12-01,Passed,52.0,115.0,Poor
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11,Passed,97.0,NaN,Poor
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26,Passed,102.0,176.0,Good
7,ST008,Gauri,23,Nagpur,Mechanical,42.0,57.0,7,Not Placed,2024-08-17,Passed,47.0,99.0,Poor
8,ST009,Vivek,20,NaN,Mechanical,44.0,79.0,12,Interviewing,2023-11-29,Passed,49.0,123.0,Good
9,ST010,Nisha,20,Mumbai,ENTC,51.0,97.0,12,Not Placed,2023-08-23,Passed,56.0,148.0,Excellent
10,ST011,Aditya,20,Nagpur,Mechanical,67.0,79.0,5,Not Placed,2024-07-25,Passed,72.0,146.0,Good
11,ST012,Sara,21,Kolhapur,Computer,NaN,75.0,15,Interviewing,2023-09-17,Fail,NaN,NaN,Good
12,ST013,Om,21,Aurangabad,IT,79.0,86.0,18,Not Placed,2023-10-05,Passed,84.0,165.0,Good
13,ST014,Priya,22,Kolhapur,ENTC,85.0,90.0,29,Not Placed,2023-12-03,Passed,90.0,175.0,Poor
14,ST015,Kunal,22,Aurangabad,Computer,52.0,63.0,5,Placed,2023-08-18,Passed,57.0,115.0,Poor
15,ST016,Ira,23,Solapur,ENTC,78.0,65.0,6,Not Placed,2023-12-13,Passed,83.0,143.0,Poor
16,ST017,Rahul,22,Kolhapur,ENTC,76.0,84.0,2,Placed,2024-05-15,Passed,81.0,160.0,Good
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20,Passed,99.0,NaN,Poor
18,ST019,Dev,23,Kolhapur,ENTC,67.0,55.0,13,Placed,2024-08-19,Passed,72.0,122.0,Poor
19,ST020,Pooja,23,Nagpur,IT,78.0,74.0,25,Not Placed,2024-03-03,Passed,83.0,152.0,Poor
20,ST021,Arjun,18,Satara,Civil,NaN,88.0,3,Placed,2024-09-18,Fail,NaN,NaN,Good
21,ST022,Maya,19,Pune,IT,61.0,74.0,7,Placed,2024-06-09,Passed,66.0,135.0,Poor
22,ST023,Neel,22,Nashik,IT,69.0,59.0,32,Not Placed,2023-10-14,Passed,74.0,128.0,Poor
23,ST024,Tara,21,Nagpur,ENTC,71.0,93.0,14,Interviewing,2023-12-22,Passed,76.0,164.0,Excellent
24,ST025,Yash,20,Aurangabad,ENTC,80.0,96.0,30,Placed,2023-10-05,Passed,85.0,176.0,Excellent
25,ST026,Aditi,20,Pune,ENTC,52.0,59.0,16,Not Placed,2023-06-04,Passed,57.0,111.0,Poor
26,ST027,Sahil,23,Pune,IT,42.0,100.0,6,Placed,2024-08-14,Passed,47.0,142.0,Excellent
27,ST028,Riya,22,Nagpur,Mechanical,59.0,59.0,33,Not Placed,2024-03-03,Passed,64.0,118.0,Poor
28,ST029,Manav,22,Aurangabad,IT,46.0,91.0,32,Not Placed,2023-09-06,Passed,51.0,137.0,Excellent
29,ST030,Kavya,23,Solapur,Mechanical,44.0,61.0,29,Not Placed,2024-01-26,Passed,49.0,105.0,Poor

Create performance: Excellent (90+), Very Good (80–89), Good (70–79), Average (60–69), Needs Improvement (below 60).

In [16]:
students['attendance'].apply(lambda x: 'Excellent' if x > 90 else 'Very Good' if x >=80 and x < 89 else 'Good' if x >=70 and x < 79 else 'Average' if x >= 60 and x < 69 else 'Improvement Needed'   )

0                Average
1              Excellent
2                Average
3              Excellent
4                Average
5     Improvement Needed
6     Improvement Needed
7     Improvement Needed
8     Improvement Needed
9              Excellent
10    Improvement Needed
11                  Good
12             Very Good
13    Improvement Needed
14               Average
15               Average
16             Very Good
17    Improvement Needed
18    Improvement Needed
19                  Good
20             Very Good
21                  Good
22    Improvement Needed
23             Excellent
24             Excellent
25    Improvement Needed
26             Excellent
27    Improvement Needed
28             Excellent
29               Average
Name: attendance, dtype: str

Find the total number of students who passed.

In [17]:
students[students['Passed'] == 'Passed'].count()

student_id              27
name                    27
age                     27
city                    26
course                  27
marks                   27
attendance              25
study_hours_per_week    27
placement_status        27
join_date               27
Passed                  27
bonus_marks             27
total_score             25
attendance_status       27
dtype: int64

In [18]:
students[students['Passed'] == 'Fail'].count()

student_id              3
name                    3
age                     3
city                    3
course                  3
marks                   0
attendance              3
study_hours_per_week    3
placement_status        3
join_date               3
Passed                  3
bonus_marks             0
total_score             0
attendance_status       3
dtype: int64

Find the percentage of students who passed, excluding missing marks from the denominator.

In [19]:
students['bonus_marks'].apply(lambda x : (x /100)*100)

0      83.0
1      49.0
2      48.0
3       NaN
4      52.0
5      97.0
6     102.0
7      47.0
8      49.0
9      56.0
10     72.0
11      NaN
12     84.0
13     90.0
14     57.0
15     83.0
16     81.0
17     99.0
18     72.0
19     83.0
20      NaN
21     66.0
22     74.0
23     76.0
24     85.0
25     57.0
26     47.0
27     64.0
28     51.0
29     49.0
Name: bonus_marks, dtype: float64

Find the average marks of students who passed.

In [20]:
students.loc[students['marks'] >= 40, 'marks'].mean()

np.float64(64.37037037037037)

Find the average marks of students who failed.

In [21]:
students.loc[students['marks'] < 40, 'marks'].mean()

nan

Round average attendance to one decimal place.

In [22]:
round(students['attendance'].mean(), 1)

np.float64(76.8)

Create a column that indicates whether marks are above the class average.

In [23]:
students["Marks_Indication"] = students['marks'].apply(lambda x: 'Excellent' if x > 90 else 'Good' if x >=75 and x < 90 else 'Poor' )

Find students whose marks are within 5 points of the maximum mark.

In [24]:
students[students['marks'] >= students['marks'].max() - 5]

,student_id,name,age,city,course,marks,attendance,study_hours_per_week,placement_status,join_date,Passed,bonus_marks,total_score,attendance_status,Marks_Indication
5,ST006,Anaya,22,Kolhapur,Computer,92.0,NaN,31,Placed,2024-10-11,Passed,97.0,NaN,Poor,Excellent
6,ST007,Rohan,18,Kolhapur,ENTC,97.0,79.0,25,Not Placed,2024-05-26,Passed,102.0,176.0,Good,Excellent
17,ST018,Sana,20,Satara,Computer,94.0,NaN,20,Not Placed,2023-08-20,Passed,99.0,NaN,Poor,Excellent

Calculate the ratio of marks to weekly study hours, safely handling zero hours.

In [25]:
students['marks_per_hour'] = (
    students['marks'] / students['study_hours_per_week'].replace(0, float('nan'))
)

Create a reusable function that classifies marks into performance categories.

In [26]:
def classify_performance(marks):
    if marks >= 90:
        return 'Excellent'
    elif marks >= 80:
        return 'Very Good'
    elif marks >= 70:
        return 'Good'
    elif marks >= 60:
        return 'Average'
    else:
        return 'Poor'

In [27]:
students['performance'] = students['marks'].apply(classify_performance)